# Generated by Django 4.0.1 on 2022-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='info',
            name='unique_user_exchange',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='access_id',
            new_name='coinex_access_id',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='secret_key',
            new_name='coinex_secret_key',
        ),
        migrations.RemoveField(
            model_name='info',
            name='exchange',
        ),
        migrations.AddField(
            model_name='info',
            name='kucoin_key',
            field=models.CharField(default=3, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='kucoin_passphrase',
            field=models.CharField(default=3, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='kucoin_secret',
            field=models.CharField(default=3, max_length=128),
            preserve_default=False,
        ),
    ]
