# Generated by Django 4.0.1 on 2022-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_info_unique_user_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='coinex_access_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='coinex_secret_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='kucoin_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='kucoin_passphrase',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='kucoin_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
